### ISSUE TITLE
Arduino's library manager is out of sync

### ISSUE THREAD

**Issue by DomAmato** [PaulStoffregen/OneWire#10]
When downloading using the library manager the most recent version is 2.3.0  

![capture2](https://cloud.githubusercontent.com/assets/6936055/12188089/a8d23388-b577-11e5-8d9b-a3a0b7272512.PNG)

**Comment by PaulStoffregen** [comment]
Report this to Arduino.

**Comment by Testato** [comment]
Are you using ESP core ?
If yes, the problem is on esp side, because onewire library  is modified
but whit the same name
Il 08 gen 2016 7:46 AM, "Paul Stoffregen" <notifications@github.com> ha
scritto:

**Comment by PaulStoffregen** [comment]
Please report this to the ESP project.  If they have an old copy, ask them to update.
