### ISSUE TITLE
volatile IO_REG_TYPE *reg IO_REG_BASE_ATTR = baseReg

### ISSUE THREAD

**Issue by Serega88kos** [PaulStoffregen/OneWire#116]
Hi all. Tried various boards. All versions of the library. 

Logs Arduino IDE
..\libraries\OneWire\OneWire.cpp: In member function 'uint8_t OneWire::reset()':
..\libraries\OneWire\OneWire.cpp:167:24: error: unused variable 'reg' [-Werror=unused-variable]
  volatile IO_REG_TYPE *reg IO_REG_BASE_ATTR = baseReg;
                        ^~~
..\libraries\OneWire\OneWire.cpp: In member function 'void OneWire::write_bit(uint8_t)':
..\libraries\OneWire\OneWire.cpp:201:24: error: unused variable 'reg' [-Werror=unused-variable]
  volatile IO_REG_TYPE *reg IO_REG_BASE_ATTR = baseReg;
                        ^~~
..\libraries\OneWire\OneWire.cpp: In member function 'uint8_t OneWire::read_bit()':
..\libraries\OneWire\OneWire.cpp:229:24: error: unused variable 'reg' [-Werror=unused-variable]
  volatile IO_REG_TYPE *reg IO_REG_BASE_ATTR = baseReg;
                        ^~~
cc1plus.exe: some warnings being treated as errors
exit status 1
Compilation error for board DOIT ESP32 DEVKIT V1.

#include <OneWire.h>
#include "DallasTemperature.h"
#define ONE_WIRE_BUS 15
OneWire oneWire(ONE_WIRE_BUS);
DallasTemperature ds(&oneWire);

void setup() {
  Serial.begin(115200);
  ds.begin();
}
void loop() {
  ds.requestTemperatures();
  float temp = ds.getTempCByIndex(0);
  Serial.println(temp);
}

**Comment by PaulStoffregen** [comment]
Does it work if you delete that line?  Or compile without -Werror?

**Comment by Serega88kos** [comment]
//	volatile IO_REG_TYPE *reg IO_REG_BASE_ATTR = baseReg;
commented out three lines.
compilation completed.
