### ISSUE TITLE
Example won't work on LEONARDO?

### ISSUE THREAD

**Issue by GraemeTownsend** [PaulStoffregen/OneWire#16]
Hi,

I'm trying to get an example of the OneWire and OneWire Slave going.

Using your "DS18x20_Temperature" on a LEONARDO. Works fine. I Can see real DS18B20's on the OneWire no problem.

Using the various slave example code/projects Pro Micro board, I get no response. (Just a spit out of the temp on one of them), and the Master never see's it.

If I attach a real DS18B20 the Master see's it instantly and starts to display the value. 

Is this a hardware issue or is there something else I should try.

Regards,
Graeme.

**Comment by PaulStoffregen** [comment]
I don't maintain the OneWireSlave lib.
