### ISSUE TITLE
Work with SAM3A4C and SAM3A8C processor

### ISSUE THREAD

**Issue by varlux** [PaulStoffregen/OneWire#20]
I normally use this library with my Arduino UNO. Now I would like to use this library with SAM3A4C or SAM3A8C processor, but it seems not work....
We are discussing this issue [in this repository](https://github.com/geolink/opentracker/issues/57).
And I invite you to find a solution!

Thanks

**Comment by PaulStoffregen** [comment]
I do not have this hardware, and even if I did have it here, I probably could not spend engineering time to test it.

Please feel free to investigate this problem.  When/if you find a solution, submit a pull request.  Your changes should be limited to the hardware defines in OneWire.h.
