### ISSUE TITLE
error: #error "Please define I/O register types here"

### ISSUE THREAD

**Issue by bcraigie** [PaulStoffregen/OneWire#25]
Using an MKR1000, the library fails to compile

```
libraries\OneWire/OneWire.h:108:2: error: #error "Please define I/O register types here"

 #error "Please define I/O register types here"

  ^

exit status 1
Error compiling for board Arduino/Genuino MKR1000.
```

What can I do to get this to compile for the MKR1000 please?

Thanks

**Comment by bcraigie** [comment]
Ah, I see the problem.  On page http://playground.arduino.cc/Learning/OneWire if you click the link [latest version of the library](http://www.pjrc.com/teensy/arduino_libraries/OneWire.zip) it gives an old version.

**Comment by PaulStoffregen** [comment]
I've updated the link.
