### ISSUE TITLE
Source code license

### ISSUE THREAD

**Issue by cfobel** [PaulStoffregen/OneWire#29]
Please consider specifying the license that this project's source code is released under.

**Comment by PaulStoffregen** [comment]
License info can be found in the code.

This is a very old project with many contributors who can no longer be reached.  I am not touching anything about the license.

**Comment by cfobel** [comment]
Thanks so much for your prompt response.

My apologies, I had only looked for the license in the header file.  I now see the info that you reference in the CPP file.
