### ISSUE TITLE
Pins not reading on NodeMCU, they do work on library version 2.3.0 though

### ISSUE THREAD

**Issue by jamierf** [PaulStoffregen/OneWire#35]
I'm not sure what changed but on my NodeMCU  ESP8266 device the only pin that works with 2.3.3 is D4 - GPIO 2   Reverting the library back to version 2.3.0 fixes the issue.   This is attempting to read from a DS18B20.     Pin D2 is the one I'm using for testing but verified D4 is the only one working with the 2.3.3

I get no devices found on the other pins.

**Comment by PaulStoffregen** [comment]
Sorry, I do not use ESP.

I am depending on the ESP community to contribute high quality code.  I have merged pull requests from people who said their code worked.  That is the best I can do.  I can not help directly with any ESP board like NodeMCU.

Please ask on the ESP community forums.  Please DO NOT create more issues here for project troubleshooting for ESP boards.  I can not help with that.
