### ISSUE TITLE
OneWire lib dont work on Arduino Nano Every (ATMEGA4809)

### ISSUE THREAD

**Issue by PI-Beginner** [PaulStoffregen/OneWire#72]
OneWire Library don't work on new Arduino Nano Every with ATMEGA4809

Can you update?

Thanks!

**Comment by eclispe** [comment]
This is fixed in the repository, there just hasn't been a release to push it in to the library manager yet. Manually installing the library worked for me.

**Comment by reardencode** [comment]
@PaulStoffregen Any chance of pushing a release for ATMEGA4809 users? :)

**Comment by PaulStoffregen** [comment]
Done!
https://github.com/PaulStoffregen/OneWire/releases/tag/v2.3.5
